version: '3.8'
services:
  esp32-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./public:/usr/src/app/public
    environment:
      - NODE_ENV=production
